### PR TITLE
Fix: Default model converter should be able to handle different object types

### LINKED ISSUE #67: Default model converter should be able to handle different object types
Where an index supports multiple querysets of different object types, the default `EmbeddableFieldsVectorIndexMixin` currently throws a "All querysets must be of the same model to use the default converter" error.

Ideally this default converter should know how to handle different object types out of the box.

### PR DESCRIPTION
**Pull request by ababic**
Resolves #67 

This PR adds native support for indexes with multiple models, and modifies the `EmbeddableFieldsDocumentConverter` class to use [Django's content types framework](https://docs.djangoproject.com/en/5.0/ref/contrib/contenttypes/) to figure out which models to work with.

We can also remove the steps from the docs that instruct developers to make overrides in their custom classes.

### CODE REVIEW

**Comment by ababic** [comment]
Thanks @tomusher.

It makes sense to me that converter instances are tied to a single model class only, but I think there would be legs in updating `search()` and `find_similar()` to group documents by type, sending them off to separate converters for conversion, then reassembling them in the same order? 

As you say, I think it would make sense to tackle separately.

**Comment by tomusher** [comment]
> It makes sense to me that converter instances are tied to a single model class only, but I think there would be legs in updating `search()` and `find_similar()` to group documents by type, send them off to separate converters for conversion, then reassemble them in the correct order?

I feel like this means the index needs to know too much about the structure of a particular Document, but can see the appeal. My initial thinking was that converters are *not* tied to a single model class and can do whatever they need to convert indexed documents back to whatever the application needs to consume.

Could you add some documentation on the 'Indexing across models' section mentioning that `query` etc. will return instances of the base class?

**Comment by ababic** [comment]
@tomusher Thinking on this some more... your plan makes more sense! We might as well update EmbeddableFieldsDocumentConverter.

**Comment by tomusher** [comment]
This looks great to me @ababic - really appreciate the time you've spent on this, it will make the package much more usable, thank you!

**Pull request merged**
